# Generated by Django 2.0.13 on 2020-02-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(max_length=10)),
                ('data_name', models.CharField(max_length=200)),
                ('data_class', models.CharField(default='None', max_length=200)),
                ('data_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_class', models.CharField(max_length=100)),
                ('project_create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
