# Generated by Django 2.0.13 on 2020-02-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='project_id',
            field=models.IntegerField(),
        ),
    ]
